#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         5
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# autostarts
polybar default
feh --bg-fill ~/.config/bg.jpg
dunst

# sudo apt install dunst libnotify-bin
# You can use xrandr -q or bspc query -M to find the monitor names. 
